// <auto-generated />
namespace TrainingHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSupervisor2Course : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSupervisor2Course));
        
        string IMigrationMetadata.Id
        {
            get { return "201712062139398_AddSupervisor2Course"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
